# Configuration section.
# "template" and "resource" are required.
---
# Command templates.
# {param} to replace by value: {param} -> value
# [param] to replace by key and value: [param] -> --key value
# param not specified with either {param} and [param], but appearing in param choice will only
# affect {_name} and {_output}
# reserved params:
# {_name}: name of param choices
# {_output}: /{--output}/{_name}
# {_datetime}: current date&time
template:
  train: >
    echo python train.py {temp} [ffn-dim] [arch] --logdir {_output}
  test: >
    echo python test.py --output_dir {_output}

# rename a group of parameters for easier readability
# Applicable only for [param]s
alias:
  # list for alias by name, inherit value.
  # ffn-embed=666 will results in encoder-ffn-embed-dim=decoder-ffn-embed-dim=666
  ffn-embed: [ encoder-ffn-embed-dim, decoder-ffn-embed-dim ]
  embed-dim: [ encoder-embed-dim, decoder-embed-dim ]
  # dict for alias by name and value, inherit value and param type
  # arch=preln will be replaced as encoder-normalize-before=True, decoder-normalize-before=True
  arch: # remap
    preln: { encoder-normalize-before: True, decoder-normalize-before: True }
    postln: { encoder-normalize-before: False, decoder-normalize-before: False }

default:
  temp: data/sdf/sdf/asdf/asdf/asdf/asdfasdf/
  ffn-dim: 222
  arch: preln

# gpu indices to be filled in CUDA_VISIBLE_DEVICES={}. each resource is assigned to a worker.
# for multi-gpu tasks, simply set [ "1,2", "3,4" ]
# a single resource can be assigned multiple times, typically when your task requires a very low gpu utilization
# [ "1", "2", "3", "1", "2", "3" ]
resource: [ "1", "2", "3" ]

# list all possible choices here, model_tuner.py will sweep all possible combinations.
---
# parameter choices 1
temp: [ tuner/tune.py ]
arch: [ preln, postln ]
ffn-dim: [ 666, 555, 333 ]

---
# parameter choices 2, duplication of 1. This will be filtered out.
temp: [ hahaha ]
arch: [ preln, postln ]
ffn-dim: [ 666, 555, 333 ]

---
# parameter choices 3
temp: [ 3 ]
arch: [ preln, postln ]
ffn-dim: [ 768, 584 ]

